services:
  app:
    container_name: ftblr-app
    build: .
    ports:
      - "8084:8084"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/FTBLR_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=rajabarca
    depends_on:
      - db
    restart: always

  db:
    container_name: Ftblr
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rajabarca
      POSTGRES_DB: FTBLR_db
    ports:
      - "5431:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin-Ftblr
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: yassine@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "8080:80"

volumes:
  db_data:
