services:

  db:
    container_name: Ftblr
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: rajabarca
      POSTGRES_DB: FTBLR_db
    ports:
      - "5431:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  pgadmin:
    container_name: pgadmin-Ftblr
    image: dpage/pgadmin4:latest
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: yassine@gmail.com
      PGADMIN_DEFAULT_PASSWORD: 123456
    ports:
      - "8080:80"


volumes:
  db_data: