spring.application.name=FTBLR
server.port=8084

# DATABASE - PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5431/FTBLR_db
spring.datasource.username=postgres
spring.datasource.password=rajabarca
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA / HIBERNATE
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# LOGGING
logging.level.root=INFO
logging.level.org.example.ftblr=DEBUG
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE



ftblr.app.jwtSecret=6ZR5kL9pX2mN8qR3vY7wB4cE1tA6fD0gH3jK8mL9nP2qR5sT8vW4yZ7cB0fD3gH6
ftblr.app.jwtExpirationMs=86400000